### ISSUE TITLE
Error when it connects to tacview

### ISSUE THREAD

**Issue by DragonDal** [Frigondin/DCSBattleground#1]
I started as per instructions work fine now it gets an error , now it does not work.

> PowerShell 7.4.1
PS C:\Users\hsgru> cd C:\DCS\BattleGround
PS C:\DCS\BattleGround> DCSBattleground.exe --config config.json --bind 0.0.0.0:8080
The database is connected
2024/02/01 12:49:36 Starting up 1 Tacview clients
2024/02/01 12:49:41 [session:Dragon] tacview client session initialized
panic: pq: relation "bg_geometry" does not exist

goroutine 18 [running]:
github.com/b1naryth1ef/sneaker/server.CheckError(...)
        C:/Tool/DCSBattleground/server/http.go:411
github.com/b1naryth1ef/sneaker/server.(*serverSession).runSharedGeometry(0xc0001b1650)
        C:/Tool/DCSBattleground/server/session.go:255 +0xea9
github.com/b1naryth1ef/sneaker/server.(*serverSession).updateLoop(0xc0001b1650)
        C:/Tool/DCSBattleground/server/session.go:139 +0x265
created by github.com/b1naryth1ef/sneaker/server.(*serverSession).run
        C:/Tool/DCSBattleground/server/session.go:192 +0x56
PS C:\DCS\BattleGround>

>

**Comment by Frigondin** [comment]
Hello, you need to enable the DCSBattleground's plugin on the SpecialK Server bot.
![image](https://github.com/Frigondin/DCSBattleground/assets/132273581/703df4e0-80cb-4512-923a-4bd854b12f53)

**Comment by gmccabe** [comment]
So SpecialK Server bot is required then regardless of the config? I am having the same issue with the setting "serverbot": false.

**Comment by Frigondin** [comment]
Hello, can you check without the database parameter please ?

**Comment by gmccabe** [comment]
The same error either with either database not defined in the config or empty.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x558973]

goroutine 18 [running]:
database/sql.(*DB).conn(0x0, {0xda39c8, 0xc00001c108}, 0x1)
        C:/Program Files/Go/src/database/sql/sql.go:1282 +0x53
database/sql.(*DB).PingContext.func1(0x2c?)
        C:/Program Files/Go/src/database/sql/sql.go:850 +0x45
database/sql.(*DB).retry(0x197?, 0xc00009b768)
        C:/Program Files/Go/src/database/sql/sql.go:1538 +0x47
database/sql.(*DB).PingContext(0x0, {0xda39c8, 0xc00001c108})
        C:/Program Files/Go/src/database/sql/sql.go:849 +0x98
database/sql.(*DB).Ping(...)
        C:/Program Files/Go/src/database/sql/sql.go:867
github.com/b1naryth1ef/sneaker/server.(*serverSession).runSharedGeometry(0xc00019d570)
        C:/Tool/DCSBattleground/server/session.go:239 +0x7e
github.com/b1naryth1ef/sneaker/server.(*serverSession).updateLoop(0xc00019d570)
        C:/Tool/DCSBattleground/server/session.go:139 +0x265
created by github.com/b1naryth1ef/sneaker/server.(*serverSession).run
        C:/Tool/DCSBattleground/server/session.go:192 +0x56
